### ISSUE TITLE
Add Functionality of removing keys from OpenSRP Cache 

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-core#137]
- [x] Allow cache eviction of keys

- [x] Fix NPE bug on trying to access location attribute when attributes are null

**Comment by craigappl** [comment]
@githengi , I'm not sure how to test this for QA

**Comment by githengi** [comment]
This cannot can't easily be tested on the UI but can be checked on this PR [https://github.com/OpenSRP/opensrp-client-core/pull/138](https://github.com/OpenSRP/opensrp-client-core/pull/138)
