### ISSUE TITLE
Improve Show password checkbox on login

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-core#148]
The show password checkbox needs to be improved. This applies to all OpenSRP projects, including WCARO and ANC.

The white checkbox needs to be enlarged to show the full check mark. Right now, the check mark gets cut off by the checkbox.

The tappable area needs to be improved as well. It is very difficult to check it right now.

@keymane pls re-assign the issue to whoever required.

**Comment by rkodev** [comment]
Increased the size of the checkbox to decrease difficulty in checking it.
Ensured that the check mark is inside the checkbox

**Comment by faith-mutua** [comment]
QA results - 29th Jan

The issue seems to have been resolved in WCARO.  The checkbox can now be checked with ease.

**Comment by cagulas** [comment]
Lgtm
