### ISSUE TITLE
Validate Authorization before Sync

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-core#156]
- [x] Validate the users authorization on openmrs before Sync.

- [x] Add configuration to determine whether to sync the offline data to server before logging user off

- [x] Notify use that they have been logged off because account has been disabled

Currently after disabling or deleting a users account on OpenMRS, users are still able to login in the previously logged in devices

Fixes [https://github.com/OpenSRP/opensrp-client-reveal/issues/57](https://github.com/OpenSRP/opensrp-client-reveal/issues/57)

**Comment by craigappl** [comment]
Passed QA
