### ISSUE TITLE
Implement Interface for retrieving data to be sent in P2P Library

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-core#190]
Implement interface for retrieving data that should be send during P2P sync.

[https://github.com/OpenSRP/opensrp-client-p2p/issues/10](https://github.com/OpenSRP/opensrp-client-p2p/issues/10)

The class will handle logic for getting the different objects e.g EventClients, and Multi Media images,  etc

**Comment by githengi** [comment]
Reduced to 1 day because only EventClients, and Multi Media images will be supported and there are underlying libraries in core already.

**Comment by ekigamba** [comment]
Done in #210
