### ISSUE TITLE
Update SQLite rowid on update to make records immutable

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-core#192]
As per SQLite [documentation ](https://www.sqlite.org/autoinc.html) Whenever you create a table without specifying the WITHOUT ROWID option, you get an implicit auto increment column called `rowid`.

On updating either of below tables update the `rowid` to the maximum of that table +1. This makes updates for each object immutable. 
- [x] Events, 
- [x] Clients
- [ ] ImageList

The `rowId` will be used by P2PLibrary to identify records that should be synced

**Comment by ekigamba** [comment]
It seems that the records into imagelist are only added and not updated. Adding an image to it should add the rowid with the max int **UNTIL** the table is full
