### ISSUE TITLE
Update sync tables 

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-core#26]
Related to https://github.com/OpenSRP/opensrp-client-path/issues/125
update sync tables
- [x] add a validate status column
- [x] add indexes for the search columns

**Comment by mib-iqbal** [comment]
Hi @keymane any update on this?

**Comment by keymane** [comment]
Yes this is done. Checkout https://github.com/OpenSRP/opensrp-client-path/pull/132

**Comment by mib-iqbal** [comment]
is there any change in the server code for this feature to function properly?
