### ISSUE TITLE
App lock out issue when offline

### ISSUE THREAD

**Issue by cafootitt** [OpenSRP/opensrp-client-core#267]
During the Togo training, a number of users have been locked out of the app for no obvious reason. 

We made sure of the following:
- The user had already logged in previously with an internet connection
- The user did not change the device date/time settings in between login attempts

What we know:
- This only happens when the user is offline
- Usually, they can log in when we connect the device to the internet (although in one instance this didn't work)
- We can always log back in after clearing the app data

This is high priority, because we need to ensure the app reliably works offline, all the time.

Assigning to @ndegwamartin and @githengi for now until they can assess it and re-assign if needed.

**Comment by ndegwamartin** [comment]
Could be related to this issue: https://stackoverflow.com/questions/48290355/unrecoverablekeyexception-failed-to-obtain-information-about-private-key-keysto

**Comment by cafootitt** [comment]
Cool, it does sound like it, we'd have to test this next. Does this share a workaround for the user who gets this problem?

**Comment by Andati** [comment]
So this issue happens when screen lock setting in Android security settings is set to **None** or **Swipe**. It does not appear when the screen lock is set to PIN, Password or Pattern.

There is an android issue on the same [here](https://issuetracker.google.com/issues/36983155 ).

[This](https://doridori.github.io/android-security-the-forgetful-keystore/#sthash.MsFkA9xB.dpbs) article explains technically how the security settings are affecting the Android Keystore

**Comment by cafootitt** [comment]
@Andati great, thanks. So in the meantime, the workaround is to set it to something other than none or swipe?

Also, all the tablets were set to swipe for the training, and this setting wasn't changed at all during the training. The description on the link you shared makes it sound like the situation only occurs when the setting is changed. Is that the case?

**Comment by Andati** [comment]
Yes, the workaround, for now, is to set the screen lock to pattern, PIN or password.

The changing of screen lock to None or Swipe is causing the issue intermittently as well. But doing so I have been able to reproduce in a tablet and emulators.

**Comment by cafootitt** [comment]
Replaced with implementation issue: https://github.com/OpenSRP/opensrp-client-core/issues/283
