### ISSUE TITLE
Handle crashes from form invalid forms, sub-forms, rules & properties files

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-core#527]
- [ ] Add a global error handler insider the JSON Form activity (Than can rethrow the exception if it is not handled) **_(Moved)_**
- [x] Enable rollback to previous version via a user prompt
- [x] Inform the user that the rollback is going to happen -> If a previous version is available
- [ ] Add a method that receives thrown exceptions . One param should say if the error should be rethrown if not handled (This will work for silent exceptions on native-form that should work as is for current applications but revert to previous form on doc-config enabled apps)**_(Moved)_**
- [ ] There will be a activity/global error handler that handles uncaught exceptions i.e. RuntimeExceptions which cause crashing and ask the user if it can revert to the previous stable form for that app version. A different app version might mean that the data model is different and is therefore not compatible with the fallback form.**_(Moved)_**
- [ ] This global/activity error handler is limited to uncaught exceptions whereas many exceptions are handled inside native form **_(Moved)_**
- [x] Fatal errors & syntax errors are caught before opening the form - This can be handled to mean the new form is unstable
- [ ] ~Handle exceptions due to missing rules files & sub-form files - This exception will be passed over to the activity error handler~ We do not have a way to handle this since there will always be a default asset file. The developers of native-form should handle wrong references when the returned JSONObject is null or rules doesn't contain anything
- [x] Handle exceptions due to syntactic error in rules files & sub-form files & pass them over to the activity error handler
- [x] No fatal error would occur inside the JsonFormActivity due to form content

**Comment by ekigamba** [comment]
To be discussed to figure out the scope of the issue

**Comment by ekigamba** [comment]
Notes from tech team discussion

> - There will be a activity/global error handler that handles uncaught exceptions i.e. RuntimeExceptions which cause crashing and ask the user if it can revert to the previous stable form for that app version. A different app version might mean that the data model is different and is therefore not compatible with the fallback form.
> - This global/activity error handler is limited to uncaught exceptions whereas many exceptions are handled inside native form
> - Fatal errors & syntax errors are caught before opening the form - This can be handled to mean the new form is unstable
> - Handle exceptions due to missing rules files & sub-form files - This exception will be passed over to the activity error handler
> - Handle exceptions due to syntactic error in rules files & sub-form files & pass them over to the activity error handler
> - No fatal error would occur inside the JsonFormActivity due to form content

**Comment by ekigamba** [comment]
Moved remaining tasks to https://github.com/OpenSRP/opensrp-client-core/issues/536. These tasks are awaiting evaluation & scoping by native form members

**Comment by dubdabasoduba** [comment]
@ekigamba Do we have an LOE for this?

**Comment by ekigamba** [comment]
@dubdabasoduba This is already done
