### ISSUE TITLE
Verify assigned plans and jurisdictions

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-core#640]
- [x] During initial login save user assigned organizations plans and jurisdictions

- [x] After sync completes download user assigned organizations plans and jurisdictions

- [x] If user assignment has changed i.e there is changes to assigned organizations plans and jurisdictions then logoff the user and trigger remote login on next login attempt.

- [x] If user assignment changed and plans or locations were removed and all the data was synced remove the plans, locations, structures , events and clients linked to removed plans or locations

- [x] If new locations were added we would need to reset sync to start from beginning so that data for the newly assigned locations is downloaded

- [x] Use jurisdiction Ids to sync Jurisdictions instead of names

related to https://github.com/OpenSRP/opensrp-client-reveal/issues/999

**Comment by githengi** [comment]
If we future instead of resetting sync globally we may need to add functionality to just download for the new locations/plans/organizations from the beginning and then resuming normal sync so that existing assignments on the device are not downloaded again

**Comment by craigappl** [comment]
1. I recommend that we add a pop-up message telling the user that their permissions have changed and we need them to login again for them to take effect.

2. "If new locations were added we would need to reset sync to start from beginning so that data for the newly assigned locations is downloaded" Please confirm this means new plan.jurisdictions

3. I don't understand what is meant by "reset sync". Can you describe this more in the issue? Are we deleting any data as a result and will this cause a major download of information?

**Comment by githengi** [comment]
> 1. I recommend that we add a pop-up message telling the user that their permissions have changed and we need them to login again for them to take effect.
Yes this will be shown before the user is logged off
> 2. "If new locations were added we would need to reset sync to start from beginning so that data for the newly assigned locations is downloaded" Please confirm this means new plan.jurisdictions
Yes this implies that user was assigned access to new plans jurisdictions
> 3. I don't understand what is meant by "reset sync". Can you describe this more in the issue? Are we deleting any data as a result and will this cause a major download of information?
Reset of sync means setting the server versions on the client to 0. This will mean sync will restart afresh. This is guarantee that data that was not accessible but now is gets downloaded even it was created on older server versions

@craigappl
