### ISSUE TITLE
Reducing the records stored in ec_details table

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-core#692]
The ec_details table was meant to store extra attributes that are not stored in the register tables. It was then converted to an fts (virtual) table to enable fast searching. 

An issue with sqlite virtual tables is that while searching is first, inserting is really slow. A virtual table is converted to multiple tables in the database so inserting means inserting or caching in this tables.

The sync process currently inserts multiple attributes in the ec_details table where some are already in the register tables. We need to reduce these attributes, that is, only store what is necessary in the details table.

**Comment by githengi** [comment]
closing this as we already have functionality to disable ec_details
