### ISSUE TITLE
Remove double slashes on requests made from classes other that HttpAgent class.

### ISSUE THREAD

**Issue by bennsimon** [opensrp/opensrp-client-core#802]
There is a bug on some urls which have double slashes `//` this returns 500 error response from the server. A global fix had been added on HttpAgent class for the same  (from `v4.2.7` )... Whats is remaining is a fix to be applied on requests made from other classes e.g requests routed to Volley when downloading images,

**Comment by hilpitome** [comment]
@bennsimon we have identified that formatting could be the issue in the following files. We are working on a fix
https://github.com/opensrp/opensrp-client-core/blob/29fdb75f088889a1d51edaca1e9c2c9929c239be/opensrp-app/src/main/java/org/smartregister/util/FileUtilities.java#L98
https://github.com/opensrp/opensrp-client-core/blob/29fdb75f088889a1d51edaca1e9c2c9929c239be/opensrp-app/src/main/java/org/smartregister/domain/ProfileImage.java#L92
