### ISSUE TITLE
Deprecate/Remove Cloudant dependencies from core library

### ISSUE THREAD

**Issue by ndegwamartin** [opensrp/opensrp-client-core#848]
**Cloudant** android libraries are now deprecated and no longer used by OpenSRP implementations using the latest OpenSRP client core. Additionally, the current dependencies configured introduce some security vulnerabilities. The idea is to refactor and remove this resulting into the release of major version `5.0.0` of the client core library

**Comment by ndegwamartin** [comment]
Cloudant repo on GH : https://github.com/cloudant/sync-android

**Comment by ndegwamartin** [comment]
New Cloudant libraries: https://blog.cloudant.com/2021/06/30/Cloudant-SDK-Transition.html (No Android versions at this time)

**Comment by hilpitome** [comment]
@ndegwamartin is this done? Would you require any further support on this?

**Comment by ndegwamartin** [comment]
@hilpitome you can assist with reviewing the PR [#850](https://github.com/opensrp/opensrp-client-core/pull/850)
