### ISSUE TITLE
 Persist app specific data in the settings table rather than in the preference

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-core#90]
- [ ] Move app specific data stored in the preferences to the settings table
- [x] Add a verification check at login to check that the app data required exists and login remotely if some data is missing 
- [ ] Since we have apps already published, save both in preference and db but retrieve details from the db first
- [ ] The preference should have values that cannot be saved in the datavase

**Comment by githengi** [comment]
This is not necessary
