### ISSUE TITLE
App's Peformence issues on Android devices running on 2GB RAM and Offline feature does not work

### ISSUE THREAD

**Issue by dodosi** [OpenSRP/opensrp-client-core#923]
1. When the user starts collecting data using devices running on 2GB RAM, the app slows down where you can type a text and shows some delays. 
2. The app can allow you to log in when there is internet for the first time. But when you try it when there is no internet connection, the app does not allow that.

**Comment by Naima-Bashir** [comment]
Hi @dodosi kindly share the following in order for us to be able to support you:

- [ ] The ANC app you are using 
- [ ] Login credentials 
- [ ] Whether the app is a staging or production environment 
- [ ] The repository you are using.
- [ ] Steps on how to reproduce both tickets. Screenshots or videos would be helpful

**Comment by dodosi** [comment]
1. ANC APK can be downloaded here: https://github.com/dodosi/opensrp_rw/releases/tag/APK
2. To be provided 
3. production
4. https://github.com/dodosi/opensrp_rw
5. Run the application on devices running on 3GB RAM, start contact without closing the application, and do it for at least three clients. When you reach on tests tab, when you type some text on EditText you will observe performance issues by typing a text.
(This might be caused by validation)

**Comment by Naima-Bashir** [comment]
Hi @dodosi I have not been able to install the apk. I have tried to install it on two different devices but failed. Kindly reshare another apk

**Comment by Naima-Bashir** [comment]
I have managed to install the application , I'll share updates shortly
